image: node:16  # Choose the appropriate Node.js version

pipelines:
  default:
    - step:
        name: Install Dependencies
        caches:
          - node
        script:
          - npm install
          - npm install -g eas-cli  # Install Expo CLI globally if not already installed

    - step:
        name: EAS Update
        script:
          - eas update --branch $BITBUCKET_BRANCH --message "Automatic update from Bitbucket Pipelines on branch $BITBUCKET_BRANCH"
          - expo login --non-interactive -u $EXPO_USERNAME -p $EXPO_PASSWORD

        deployment: production